---
- name: Install pacemaker/corosync
  apt: name="{{ item }}" state=present
  with_items:
    - pacemaker
    - corosync

- name: Configure corosync cluster
  template: src=corosync.conf.j2 dest=/etc/corosync/corosync.conf
  notify:
    - restart corosync

- name: Ensure corosync is set to start at boot
  lineinfile: dest=/etc/default/corosync regexp=^START line="START=yes"

# See http://docs.openstack.org/ha-guide/controller-ha-pacemaker.html
- name: Fix pacemaker boot order
  command: update-rc.d pacemaker start 20 2 3 4 5 . stop 00 0 1 6 .

- name: Set pacemaker uid/gid
  copy: src=pacemaker dest=/etc/corosync/uidgid.d/pacemaker

- name: ensure corosync is running
  service: name=corosync state=started enabled=yes

- name: ensure pacemaker is running
  service: name=pacemaker state=started enabled=yes

#- name: test connections
#sudo crm_mon
#sudo crm configure show
#sudo crm configure show xml
#sudo crm_verify -L -V
#crm configure property stonith-enabled=false
