---
- name: Install pacemaker/corosync
  apt: name="{{ item }}" state=present
  with_items:
    - pacemaker
    - corosync

- name: Update logrotate to rotate corosync logs
  template: src=corosync.log.j2 dest=/etc/logrotate.d/corosync

- name: Install corosync cluster authkey
  copy: src="{{ pacemaker_authkey }}" dest=/etc/corosync/authkey owner=root group=root mode=0400
  when: pacemaker_encrypted

- name: Configure corosync cluster
  template: src=corosync.conf.j2 dest=/etc/corosync/corosync.conf
  notify:
    - restart HA

- name: Ensure corosync is set to start at boot
  lineinfile: dest=/etc/default/corosync regexp=^START line="START=yes"
  ignore_errors: "{{ ansible_check_mode }}"

# See http://docs.openstack.org/ha-guide/controller-ha-pacemaker.html
- name: Fix pacemaker boot order
  command: update-rc.d pacemaker start 20 2 3 4 5 . stop 00 0 1 6 .

- name: Set pacemaker uid/gid
  copy: src=pacemaker dest=/etc/corosync/uidgid.d/pacemaker
  notify:
    - restart HA

- name: Tell Pacemaker to use corosync
  copy: src=pcmk dest=/etc/corosync/service.d/pcmk
  notify:
    - restart HA

- name: Ensure services are running
  service: name="{{ item }}" state=started enabled=yes
  with_items:
    - corosync
    - pacemaker
  ignore_errors: "{{ ansible_check_mode }}"

- meta: flush_handlers

- name: Wait for cluster
  pause: seconds=30

- name: Configure cluster
  run_once: true
  command: "{{ item }}"
  with_items:
    - crm configure property stonith-enabled=false
    - crm configure property default-resource-stickiness="{{ pacemaker_default_resource_stickiness }}"
    - crm configure rsc_defaults resource-stickiness="{{ pacemaker_resource_stickiness }}"
  when: not ansible_check_mode
